version: "3.3"
services:
  web:
    build: ./
    container_name: flask-LabWeb
    ports:
      - "5000:5000"
    working_dir: /code
    volumes:
      - //f/codes/Web-Demo-20210517-Flask/web:/code
    environment: 
      FLASK_ENV: development
